spring:
  application:
    name: product-composite-service
  cloud:
    config:
      discovery:
        enabled: false

server:
  port: 8002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost