spring:
  application:
    name: turbine

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

#turbine:
#  clusterNameExpression: new String("default")
#  appConfig: PRODUCT-COMPOSITE-SERVCE, PRODUCT-SERVICE, REVIEW-SERVICE
#  combineHostPort: true