info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true

zuul:
  ignoredServices: "*"
  routes:
    productcomposite:
      path: /productComposite/**
      url: http://localhost:8002/productComposite

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO